language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-simplewebapp' ]; then cd .. && eval "mv $currentfolder generator-simplewebapp" && cd generator-simplewebapp; fi

